package com.booking_hotel.booking_service.kafka.events;

public enum EventType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    STAY_COMPLETED,
    ROOM_RESERVATION_REQUESTED,
    ROOM_RESERVATION_RELEASED,
    ROOM_RESERVED,
    ROOM_RESERVATION_REJECTED,
    PAYMENT_REQUESTED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED
}
